### ISSUE TITLE
Wireframes: PhotoItem Views, AlbumItem Views... what do these look like?

### ISSUE THREAD

**Issue by davidrunger** [zhoux10/instacation#3]
Also, FollowingItems?

**Comment by davidrunger** [comment]
FollowingItems?

**Comment by zhoux10** [comment]
OK, I've updated the views. I'm not sure what the FollowingItems view should look like... I was thinking of just putting the FollowingItems on the user's name page (user_show1.png)

**Comment by davidrunger** [comment]
Excellent! Nice work updating these.
